docmed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path, re_path
from main import views

app_name="main"

urlpatterns = [
    path("",views.home,  name="home"),
  
    path("message/<slug:doctor>/", views.message, 
          name="message"),
    path("doctor_list/", views.doctor_list, 
          name="doctor_list"),
    path("contact/", views.contact, name="contact"),
    path("register/", views.register, name="register"),
    path("logout/", views.user_logout, name="logout"),
    path("login/", views.user_login, name="login"),
    path("confirm_logout/", views.confirm_logout, 
          name="confirm_logout"),
    path("patient_profile/", views.patient_profile, 
          name="patient_profile"),
    path("patient_profile/<int:id>/", views.patient_profiles, 
          name="patient_profiles"),
    path("patient_appointment/", views.patient_appointment, 
          name="patient_appointment"),
    path("patient_payment/", views.patient_payment, 
          name="patient_payment"),
   	path("patient_medical/", views.patient_medical, 
          name="patient_medical"),
   	path("invoice/<int:id>/", views.generatePDF, 
          name="invoice"),

   	path("doctor_appointment/", views.doctor_appointment, 
          name="doctor_appointment"),
   	path("doctor_profile/", views.doctor_profile, 
          name="doctor_profile"),
   	path("doctor_prescriptions", views.doctor_prescriptions, 
          name="doctor_prescriptions"),
   	path("doctor_prescription/<int:id>", views.doctor_prescription, 
          name="doctor_prescription"),

   	path("receptionist_dashboard/", views.receptionist_dashboard, 
          name="receptionist_dashboard"),
   	path("create_appointments/", views.create_appointments, 
          name="create_appointments"),
    path("confirm_deletes/<int:id>", views.confirm_deletes, 
          name="confirm_deletes"),

    path("hr_dashboard", views.hr_dashboard, name="hr_dashboard"),
    path("doctor_profile_hr/<int:id>/", views.doctor_profile_hr, 
          name="doctor_profile_hr"),
    path("accounting", views.accounting, name="accounting"),   
    path("confirm_deletes_hr/<int:id>", views.confirm_deletes_hr, 
          name="confirm_deletes_hr"),
]

ml = [
    path("ml_models/", views.ml_models, 
          name="ml_models"),
    path("covid_symtoms_detection/", views.covid_symptoms_detection, 
          name="covid_symptoms_detection"),
    path("covid_symptoms_result/<int:result>/", views.covid_symptoms_result, 
          name="covid_symptoms_result"),
    path("covid_xray_prediction", views.covid_xray_prediction, name="covid_xray_prediction"),
    path("covid_xray_result/<slug:result>/", views.covid_xray_result, 
          name="covid_xray_result"),
    path("covid_ctscan_prediction", views.covid_ctscan_prediction, name="covid_ctscan_prediction"),
    path("covid_ctscan_result/<slug:result>/", views.covid_ctscan_result, 
          name="covid_ctscan_result"),
]


urlpatterns += ml

templates/machine_learning/covid_ctscan_prediction.html
{% extends "index.html" %}

{% block content %}

<!DOCTYPE html>
<html>
<head>
	<title>Corona CT SCAN</title>
	<link rel="icon" href="https://specials-images.forbesimg.com/imageserve/5e74f4b010380d0006bdbd41/960x0.jpg?fit=scale" type="image/gif" sizes="32x32">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<style>
		body {
			min-height: 100vh;
			position: relative;
		}
		.body::before {
			content: '';
			background: url('https://static.vecteezy.com/system/resources/previews/000/962/895/non_2x/abstract-coronavirus-background-vector.jpg');
			position: absolute;
			opacity: .8;
			top:0px;
			left:0px;
			bottom: 0px;
			right: 0px;
			background-size: cover;
			z-index: -1;
		}

		.header {
			text-align: center;
			padding: 20px;
		}

		.buttons {
			margin: 20px auto;
			padding: 20px 50px;	
			font-size: 30px;
			font-weight: bold;
			text-transform: uppercase;
			border-radius: 50px;
			color: white;
			background: rgba(0, 0, 0, .1);
			border: 1px solid lightgray;
			box-shadow: 0 0 40px 2px rgba(0, 0, 0, .4);
			text-shadow: 1px 2px 5px black;
			transition: 300ms linear;
		}

		.buttons:hover {
			background: rgba(0, 0, 0, .2);
			transition: 300ms linear;
			color: white;
		}
		
		section > form {
			max-width: 500px;
			margin: auto;
		}
		section label {
			font-size: 40px;
			font-weight: bold;
			color: white;
			text-shadow: 0 0 10px black;
		}

		section input:nth-child(1) {
			padding: 20px;
			font-size: 20px;
			color: white;
		}

		form {
			background: rgba(0, 0, 0, .4);
			border-radius: 50px;
		}
		
		form * {
			margin-top: 20px;
		}
		
		input:nth-child(1) * {
			background: lightgreen;
		}
		
		.data {
			color: white;
			max-width: 500px;
			padding: 10px;
			background: rgba(0, 0, 0, .4);
			border-radius: 50px;
			margin: auto;
			font-size: 25px;
			font-weight: bold;
			text-transform: uppercase;
			text-align: center;
		}
		.alert:nth-child(1) {
			background: transparent;
			border: none;
			outline: none;
			color: orange;
		}

		.alert1 {
			background: transparent;
			border: none;
			outline: none;
			color: yellow;
		}

		.alert, .alert1 {
			font-size: 20px;
		}

	</style>
</head>
<body>
	<div class="body">
		<div class='header'>
			<h1 class="buttons m-auto btn">Predict Covid From CT SCAN Report </h1>
		</div>
		<section>
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
				  <div class="form-group shadow p-5 mt-5">
				    <label for="exampleFormControlFile1">CT SCAN REPORT</label>
				    <input type="file" required class="text-light form-control-file" id="exampleFormControlFile1" name="file" />
				  	<input type="submit" />
				  </div>
				</form>
				<div class="data">
					{% if data == 'false' %}
						<div class="alert alert-success" role="success">
						  Upload Lungs CT SCAN Report
						</div>
					{% else %}
						<div class="alert1 alert-danger" role="alert">
						  Supports Only Lungs CT SCAN images
						</div>
					{% endif %}
				</div>
		</section>
	</div>
	<script>
	</script>
</body>
</html>

{% endblock %}

templates/machine_learning/covid_ctscan_result.html
{% extends 'index.html' %}

{% block content %}
<style>
	.parent {
		perspective: 100px;
	}

	.result {
		background: lightgreen;
		box-shadow: 5px -1px 3px rgba(0, 0, 0, .3);
		padding: 50px;
		margin: auto;
		border-radius: 10px;
		width: 180px;
		display: flex;
		text-align: center;
		position: relative;
		vertical-align: center;
		animation: ola 1000ms linear forwards; 
	}

	@keyframes ola{
		0% {
			transform: translateY(-400px) scale(.6) rotate(0deg);
		}
		70% {
			transform: translateY(40px) translateX(20px) scale(1.1) rotate(360deg);	
		}
		100% {
			transform-origin: top left;
			transform: translateY(40px) scale(1.1) translateX(20px) rotate(400deg) ;
		}
	}

	.result > h2 {
		text-align: center;
		width: 300px!important;
	}

	button {
		border-radius: 10px!important;
	}
	button:hover > a{
		color: white!important;
	}
</style>
<div class="parent">
		<div class="result">
			<h2>{{ result }} </h2>
		</div>

		<div style="position:relative; top: 250px;text-align: center;">
			<button class="btn btn-outline-primary btn-lg"><a href="{% url 'main:register' %}" style="text-decoration: none;">Sign In</a></button>
			<button class="btn btn-outline-primary btn-lg ml-3"><a href="{% url 'main:login' %}" style="text-decoration: none;">Login</a></button>
			<div class="h4 text-muted pt-4">
				Login To our Website And have an <br>
				Online appointment with the near by doctor.
			</div>

			<div class="h5  pt-4 pb-2">
				<b>Note</b>  <br>
				{% if result == "covid" %}
					You are <span style="color:red;font-weight: bolder;font-size:30px;">{{result}}</span> Positive 
					<button type="button" class="btn btn-primary">
					  COVID-19 
					</button>
				{% elif result == "viral" %}
					You just have <span style="color:red;font-weight: bolder;font-size:30px;">{{result}}</span> 
				{% else %}
					You are <span style="color:red;font-weight: bolder;font-size:30px;">{{result}}</span> 
				{% endif %}

			</div>
		</div>
</div>
{% endblock %}

templates/machine_learning/covid_symptoms_detection.html
{% extends 'index.html' %}


{% block content %}
	<style>

		.submission {
			transition: 300ms linear;
		}

		.submission:hover {
			cursor: pointer
			transform: translateY(-2px);
			transition: 300ms linear;
		}
		.form-control {
			box-shadow: -1px 3px 3px rgba(0, 0, 0, .3);
		}
	</style>
	<div style="background: lightgreen;">
		<h1 class="text-muted text-uppercase text-center p-4 h2">Tick The Symptoms you have </h1>
		<form style="padding: 5px; max-width:400px;margin: auto;background;" class="pt-2 text-center" method="POST">
			{% csrf_token %}
			<div class="form-group lead" >
			    <div class="submission px-4 py-1" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Fever</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1"  name="1">
					      </div>
					    </div>
					  </div>
						
						<!-- Tiredeness -->
				    <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Tiredness</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1"  name="2">
					      </div>
					    </div>
					  </div>

					  <!-- dry cough -->
					  <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Dry Cough</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1" name="3">
					      </div>
					    </div>
					  </div>

					  <!-- breathing issue -->

					   <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Breathing Issue</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1" name="4">
					      </div>
					    </div>
					  </div>

					  <!-- sore throat	 -->

					    <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Sore Throat</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1" name="5">
					      </div>
					    </div>
					  </div>

					  <!-- No Symptoms -->

					    <div class="" >
			    	    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="hidden" style="width:20px;height: 20px;" id="gridCheck1" name="6">
					      </div>
					    </div>
					  </div>

					  <!-- Body Pain -->

					    <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Pain</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1" name="7">
					      </div>
					    </div>
					  </div>

					  <!-- nasal congestion -->

					  <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Nasal Congestion</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1" name="8">
					      </div>
					    </div>
					  </div>

					  <!-- runnong nose -->

					  <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Running Nose</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1" name="9">
					      </div>
					    </div>
					  </div>

					  <!-- <Dirrehea></Dirrehea> -->
						
						<div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Dirrhea</div>
					    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="checkbox" style="width:20px;height: 20px;" id="gridCheck1" name="10">
					      </div>
					    </div>
					  </div>

					  <!-- No experiencing -->

					     <div class="" >
			    	    <div class="">
					      <div class="form-check">
					        <input class="form-check-input" type="hidden" style="width:20px;height: 20px;" id="gridCheck1" name="11">
					      </div>
					    </div>
					  </div>

					  <!-- age -->

					     <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Age</div>
					    <div class="">
					      <div class="form-check">
					        <select class="form-control" type="checkbox" id="gridCheck1" name="12" style="position: relative;right: -5px;">
					        	<option value="0">0 - 9</option>
					        	<option value="1">10 - 19</option>
					        	<option value="2" selected>20 - 24</option>
					        	<option value="3">25 - 59</option>
					        	<option value="4">60 + </option>
					        </select>

					      </div>
					    </div>
					  </div>


					  <!-- gender -->


					   <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, .3);display: flex!important; justify-content: space-between!important;">
			    	<div class="" style="font-weight:bolder">Gender</div>
					    <div class="">
					      <div class="form-check">
					        <select class="form-control" type="checkbox" id="gridCheck1" name="17" style="position: relative;right: -5px;">
					        	<option value="0" selected>Male</option>
					        	<option value="1">Female</option>
					        	<option value="2">Transgender</option>
				
					        </select>

					      </div>
					    </div>
					  </div>

					  <div class="submission px-4 py-2" style="box-shadow: 2px 3px 3px rgba(0, 0, 0, 0);display: flex!important; justify-content: space-between!important;">

					  		<input type="submit" class="form-control">
					    </div>
					  </div>
					  
			</div>
			    
		</form>
	</div>
{% endblock %}

templates/machine_learning/covid_symptoms_result.html
{% extends 'index.html' %}

{% block content %}
<style>
	.parent {
		perspective: 100px;
	}

	.result {
		background: lightgreen;
		box-shadow: 5px -1px 3px rgba(0, 0, 0, .3);
		padding: 50px;
		margin: auto;
		border-radius: 10px;
		width: 200px;
		display: flex;
		text-align: center;
		position: relative;
		vertical-align: center;
		animation: ola 1000ms linear forwards; 
	}

	@keyframes ola{
		0% {
			transform: translateY(-400px) scale(.6) rotate(0deg);
		}
		70% {
			transform: translateY(40px) translateX(20px) scale(1.1) rotate(360deg);	
		}
		100% {
			transform-origin: top left;
			transform: translateY(40px) scale(1.1) translateX(20px) rotate(400deg) ;
		}
	}

	.result > h2 {
		text-align: center;
		width: 300px!important;
	}

	button {
		border-radius: 10px!important;
	}
	button:hover > a{
		color: white!important;
	}
</style>
<div class="parent">
		<div class="result">
			{% if result == 0 %}
				<h2>No Risk</h2>
			{% elif result == 10 %}
				<h2>Low Risk</h2>
			{% elif result == 20 %}
				<h2> Moderate Risk</h2>
			{% else %}
				<h2>High Risk</h2>
			{% endif %}
		</div>

		<div style="position:relative; top: 250px;text-align: center;">
			<button class="btn btn-outline-primary btn-lg"><a href="{% url 'main:register' %}" style="text-decoration: none;">Sign In</a></button>
			<button class="btn btn-outline-primary btn-lg ml-3"><a href="{% url 'main:login' %}" style="text-decoration: none;">Login</a></button>
			<div class="h4 text-muted pt-4">
				Login To our Website And have an <br>
				Online appointment with the near by doctor.
			</div>

			<div class="h5  pt-4 pb-2">
				<b>Note</b>  <br>
				{% if result == 0 %}
					<span style="color:red;font-weight: bolder;font-size:30px;">No Risk</span> To 
				{% elif result == 10 %}
					<span style="color:red;font-weight: bolder;font-size:30px;">Low Risk</span> To 
				{% elif result == 20 %}
					<span style="color:red;font-weight: bolder;font-size:30px;">Moderate Risk</span> To 
				{% else %}
					<span style="color:red;font-weight: bolder;font-size:30px;">High Risk</span> To 
				{% endif %}
				
				<button type="button" class="btn btn-primary">
				  COVID-19 
				</button>
			</div>
		</div>
</div>
{% endblock %}

templates/machine_learning/covid_xray_prediction.html
{% extends "index.html" %}

{% block content %}

<!DOCTYPE html>
<html>
<head>
	<title>Corona Xray</title>
	<link rel="icon" href="https://specials-images.forbesimg.com/imageserve/5e74f4b010380d0006bdbd41/960x0.jpg?fit=scale" type="image/gif" sizes="32x32">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<style>
		body {
			min-height: 100vh;
			position: relative;
		}
		.body::before {
			content: '';
			background: url('https://www.athina984.gr/wp-content/uploads/2020/10/covid-19.jpg');
			position: absolute;
			opacity: .8;
			top:0px;
			left:0px;
			bottom: 0px;
			right: 0px;
			background-size: cover;
			z-index: -1;
		}

		.header {
			text-align: center;
			padding: 20px;
		}

		.buttons {
			margin: 20px auto;
			padding: 20px 50px;	
			font-size: 30px;
			font-weight: bold;
			text-transform: uppercase;
			border-radius: 50px;
			color: white;
			background: rgba(0, 0, 0, .1);
			border: 1px solid lightgray;
			box-shadow: 0 0 40px 2px rgba(0, 0, 0, .4);
			text-shadow: 1px 2px 5px black;
			transition: 300ms linear;
		}

		.buttons:hover {
			background: rgba(0, 0, 0, .2);
			transition: 300ms linear;
			color: white;
		}
		
		section > form {
			max-width: 500px;
			margin: auto;
		}
		section label {
			font-size: 40px;
			font-weight: bold;
			color: white;
			text-shadow: 0 0 10px black;
		}

		section input:nth-child(1) {
			padding: 20px;
			font-size: 20px;
			color: white;
		}

		form {
			background: rgba(0, 0, 0, .4);
			border-radius: 50px;
		}
		
		form * {
			margin-top: 20px;
		}
		
		input:nth-child(1) * {
			background: lightgreen;
		}
		
		.data {
			color: white;
			max-width: 500px;
			padding: 10px;
			background: rgba(0, 0, 0, .4);
			border-radius: 50px;
			margin: auto;
			font-size: 25px;
			font-weight: bold;
			text-transform: uppercase;
			text-align: center;
		}
		.alert:nth-child(1) {
			background: transparent;
			border: none;
			outline: none;
			color: orange;
		}

		.alert1 {
			background: transparent;
			border: none;
			outline: none;
			color: yellow;
		}

		.alert, .alert1 {
			font-size: 20px;
		}

	</style>
</head>
<body>
	<div class="body">
		<div class='header'>
			<h1 class="buttons m-auto btn">Predict Covid From Xray Report </h1>
		</div>
		<section>
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
				  <div class="form-group shadow p-5 mt-5">
				    <label for="exampleFormControlFile1">XRAY REPORT</label>
				    <input type="file" required class="text-light form-control-file" id="exampleFormControlFile1" name="file" />
				  	<input type="submit" />
				  </div>
				</form>
				<div class="data">
					{% if data == 'false' %}
						<div class="alert alert-success" role="success">
						  Upload Chest Xray Report
						</div>
					{% else %}
						<div class="alert1 alert-danger" role="alert">
						  Supports Only Chest Xray images
						</div>
					{% endif %}
				</div>
		</section>
	</div>
	<script>
	</script>
</body>
</html>

{% endblock %}

templates/machine_learning/covid_xray_result.html
{% extends 'index.html' %}

{% block content %}
<style>
	.parent {
		perspective: 100px;
	}

	.result {
		background: lightgreen;
		box-shadow: 5px -1px 3px rgba(0, 0, 0, .3);
		padding: 50px;
		margin: auto;
		border-radius: 10px;
		width: 180px;
		display: flex;
		text-align: center;
		position: relative;
		vertical-align: center;
		animation: ola 1000ms linear forwards; 
	}

	@keyframes ola{
		0% {
			transform: translateY(-400px) scale(.6) rotate(0deg);
		}
		70% {
			transform: translateY(40px) translateX(20px) scale(1.1) rotate(360deg);	
		}
		100% {
			transform-origin: top left;
			transform: translateY(40px) scale(1.1) translateX(20px) rotate(400deg) ;
		}
	}

	.result > h2 {
		text-align: center;
		width: 300px!important;
	}

	button {
		border-radius: 10px!important;
	}
	button:hover > a{
		color: white!important;
	}
</style>
<div class="parent">
		<div class="result">
			<h2>{{ result }} </h2>
		</div>

		<div style="position:relative; top: 250px;text-align: center;">
			<button class="btn btn-outline-primary btn-lg"><a href="{% url 'main:register' %}" style="text-decoration: none;">Sign In</a></button>
			<button class="btn btn-outline-primary btn-lg ml-3"><a href="{% url 'main:login' %}" style="text-decoration: none;">Login</a></button>
			<div class="h4 text-muted pt-4">
				Login To our Website And have an <br>
				Online appointment with the near by doctor.
			</div>

			<div class="h5  pt-4 pb-2">
				<b>Note</b>  <br>
				{% if result == "covid" %}
					You are <span style="color:red;font-weight: bolder;font-size:30px;">{{result}}</span> Positive 
					<button type="button" class="btn btn-primary">
					  COVID-19 
					</button>
				{% elif result == "viral" %}
					You just have <span style="color:red;font-weight: bolder;font-size:30px;">{{result}}</span> 
				{% else %}
					You are <span style="color:red;font-weight: bolder;font-size:30px;">{{result}}</span> 
				{% endif %}

			</div>
		</div>
</div>
{% endblock %}

templates/machine_learning/ml_models.html
{% extends 'index.html' %}


{% block content %}
<style type="text/css">
	.outer {

	}

	.inner:nth-child(1) {
		margin-top: 30px;
	}

	.inner {
		width: 100%;
		display: block;
		text-align: center;
		transition: 500ms linear;
	}

	.inner:hover {
		transform: translateY(-3px);
		opacity: .7;
		transition: 500ms linear;
	}

	button {
		border: none;
		min-width: 400px;
		border-radius: 10px;
		outline: none;
		padding: 20px 40px;
		background: orange;
		color: white;
		font-weight: bold;
		font-family: ubuntu;
		letter-spacing: 1px;
		margin: 10px;
	}

	a {
		text-decoration: none;
		color: white;
	}

	a:hover {
		text-decoration: none;
		color: white;
	}

</style>
<!--
	<a href="" class="mx-2 text-light covid">Predict Covid</a>
-->
<div class="outer">
	<div class="inner">
		<button>
			<a href="{% url 'main:covid_xray_prediction' %}">
				Predict Covid From Xray
			</a>
		</button>
	</div>
	
	<div class="inner">
		<button>
			<a href="{% url 'main:covid_ctscan_prediction' %}">
				Predict Covid From CTScan
			</a>
		</button>
	</div>

	<div class="inner">
		<button>
			<a href="{% url 'main:covid_symptoms_detection' %}">
				Predict Covid Risk Factor From Symtoms
			</a>
		</button>
	</div>
</div>
{% endblock %}