docmed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path, re_path
from main import views

app_name="main"

urlpatterns = [
    path("",views.home,  name="home"),
  
    path("message/<slug:doctor>/", views.message, 
          name="message"),
    path("doctor_list/", views.doctor_list, 
          name="doctor_list"),
    path("contact/", views.contact, name="contact"),
    path("register/", views.register, name="register"),
    path("logout/", views.user_logout, name="logout"),
    path("login/", views.user_login, name="login"),
    path("confirm_logout/", views.confirm_logout, 
          name="confirm_logout"),
    path("patient_profile/", views.patient_profile, 
          name="patient_profile"),
    path("patient_profile/<int:id>/", views.patient_profiles, 
          name="patient_profiles"),
    path("patient_appointment/", views.patient_appointment, 
          name="patient_appointment"),
    path("patient_payment/", views.patient_payment, 
          name="patient_payment"),
   	path("patient_medical/", views.patient_medical, 
          name="patient_medical"),
   	path("invoice/<int:id>/", views.generatePDF, 
          name="invoice"),

   	path("doctor_appointment/", views.doctor_appointment, 
          name="doctor_appointment"),
   	path("doctor_profile/", views.doctor_profile, 
          name="doctor_profile"),
   	path("doctor_prescriptions", views.doctor_prescriptions, 
          name="doctor_prescriptions"),
   	path("doctor_prescription/<int:id>", views.doctor_prescription, 
          name="doctor_prescription"),

   	path("receptionist_dashboard/", views.receptionist_dashboard, 
          name="receptionist_dashboard"),
   	path("create_appointments/", views.create_appointments, 
          name="create_appointments"),
    path("confirm_deletes/<int:id>", views.confirm_deletes, 
          name="confirm_deletes"),

    path("hr_dashboard", views.hr_dashboard, name="hr_dashboard"),
    path("doctor_profile_hr/<int:id>/", views.doctor_profile_hr, 
          name="doctor_profile_hr"),
    path("accounting", views.accounting, name="accounting"),   
    path("confirm_deletes_hr/<int:id>", views.confirm_deletes_hr, 
          name="confirm_deletes_hr"),
]

ml = [
    path("ml_models/", views.ml_models, 
          name="ml_models"),
    path("covid_symtoms_detection/", views.covid_symptoms_detection, 
          name="covid_symptoms_detection"),
    path("covid_symptoms_result/<int:result>/", views.covid_symptoms_result, 
          name="covid_symptoms_result"),
    path("covid_xray_prediction", views.covid_xray_prediction, name="covid_xray_prediction"),
    path("covid_xray_result/<slug:result>/", views.covid_xray_result, 
          name="covid_xray_result"),
    path("covid_ctscan_prediction", views.covid_ctscan_prediction, name="covid_ctscan_prediction"),
    path("covid_ctscan_result/<slug:result>/", views.covid_ctscan_result, 
          name="covid_ctscan_result"),
]


urlpatterns += ml

templates/card.html
{% extends 'home.html' %}

{% block card %}
	<div class="row container m-auto">
		<div class="jumbotron bg-transparent col col-12 col-sm-6 col-md-4">
			<div class="department-card" style="overflow: hidden;">
				<div style="height:200px; overflow: hidden;" >
					<img src="https://i.pinimg.com/736x/fd/a1/3b/fda13b9d6d88f25a9d968901d319216a.jpg" style="width:100%;" class="border rounded card-image">
				</div>
				<div class="ml-2">
					<p class="pl-2 pt-2">
					<h5>COVAT</h5>
					<small class="font-weight-bold text-muted " style="font-size:.8rem;">
						Highly Interactive Chatbot Who can clear all your queries related to covid 19 
						<br>
						<span class="lead font-weight-bold">Try out Covat Chat bot</span>
					</small><br>
					<button class="btn btn-outline-primary mt-3 bot-clicker">
						<span class="cobat">Talk To Cobat</span>
					</button>
				</p>
				</div>
			</div>
		</div>

		<!-- <physical therapy> -->

		<div class="jumbotron bg-transparent col col-12 col-sm-6 col-md-4">
			<div class="department-card" style="overflow: hidden;">
				<div style="height:200px; overflow: hidden;" >
					<img src="https://www.scripps.org/sparkle-assets/images/nurse_safely_checking_in_patient_1200x750-3b4614d05b007fc6044cb3a132d64212.jpg" style="width:100%;" class="border rounded card-image">
				</div>
				<div class="ml-2">
					<p class="pl-2 pt-2">
					<h5>Have Online Appointment</h5>
					<small class="font-weight-bold text-muted " style="font-size:.8rem;">
						Now it doesn't matter in which corner of the world you are you can schedule the appointment on your own.
					</small><br>
					<button class="btn btn-outline-primary mt-3">
						<span><a style="text-decoration: none" href="{% url 'main:register' %}">Appointment</a></span>
					</button>
				</p>
				</div>
			</div>
		</div>

		<!-- <dental care> -->

		<div class="jumbotron bg-transparent col col-12 col-sm-6 col-md-4">
			<div class="department-card" style="overflow: hidden;">
				<div style="height:200px; overflow: hidden;" >
					<img src="https://www.bbva.com/wp-content/uploads/2019/11/machine-learning-1920x1180.jpg" style="width:100%;" class="border rounded card-image">
				</div>
				<div class="ml-2">
					<p class="pl-2 pt-2">
					<h5>Covid Detection Ml Model</h5>
					<small class="font-weight-bold text-muted " style="font-size:.8rem;">
						If you want to detect covid based on the symptoms then 
						try our Covid Ml detector . 
						<br>
						<span class="lead font-weight-bold">It's Free</span>
					</small><br>
					<button class="btn btn-outline-primary mt-3">
						<span><a style="text-decoration: none" href="{% url 'main:covid_symptoms_detection' %}">Detect Covid</a></span>
					</button>
				</p>
				</div>
			</div>
		</div>

		<!-- <diagnostic test> -->

	</div>


	<div class="quote" style="height:100vh; overflow:hidden; position: relative;">
		<img src="https://www.cedars-sinai.org/content/dam/cedars-sinai/blog/2020/04/doctors-office-safe.jpg"
			style="width:100%; opacity: .6;"
		>

		<div class="corousal">
			<i class="fa fa-quote-right h1" style="color:wheat;" aria-hidden="true"></i>

			<p class="lead lead text-muted font-weight-bold mt-5 mb-5" style="font-size:30px;">
				
				“After you find out all the things that can go wrong, 
				<br>
				your life becomes less about living and more about waiting.” 
				<br>
			</p>
			<hr class="bg-secondary" style="width:10%;">
			<h5>
				― Chuck Palahniuk, Choke
			</>
		</div>
	</div>
{% endblock %}

templates/contact.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
	<div id="map"></div>
	<div style="position: absolute;top: 100vh;min-height:100vh">
		<div class="row pt-3 mx-auto;" style="width:80%; margin:auto!important;">
			<div class="col col-8">
				<h4 class="font-weight-bolder">
					Get in Touch 
					<hr class="bg-secondary w-25 ml-0">
				</h4>
				<br>
				<form action="" method="POST">
					{% csrf_token %}
					<div class="row">
						<div class="col col-6 ">
							<input type="text" class="form-control" name="name" placeholder="Name">
						</div>
						<div class="col col-6">
							<input type="email"  class="form-control" name="email" placeholder="Email">
						</div>
						<div class="col col-12 mt-4 ">
							<input type="text"  class="form-control" name="subject" placeholder="Subject">
						</div>
						<div class="col col-12 mt-4">
		 					<textarea class="form-control" placeholder="Message" style="height:200px;" name="message"></textarea>
						</div>
						<div class="col col-12 mt-4">
							<input type="submit" name="submit" class="btn btn-outline-primary">
						</div>
					</div>

				</form>
			</div>

			
			<div class="col col-4 pt-5 mt-4">
				<div class="row">
					<div class="col col-12 mb-4">
						<div class="row">
							<div class="col col-3 d-flex justify-content-center align-items-center">
								<i class="fas h4 fa-house-user"></i>
							</div>
							<div class="col">
								<div class="row">
									<div class="col col-12">
										<small class="font-weight-bolder" style="font-size:.9rem;">
											Begaluru, Karanataka
										</small>
									</div>
									<div class="col col-12">
										<small class="text-muted font-weight-bold">
											M S R Nagar, 150061
										</small>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col col-12 my-4 ">
						<div class="row">
							<div class="col col-3 d-flex justify-content-center align-items-center">
								<i class="fas h4 fa-phone-square-alt"></i>
							</div>
							<div class="col">
								<div class="row">
									<div class="col col-12">
										<small class="font-weight-bolder" style="font-size:.9rem;">
											+91 95927753489
										</small>
									</div>
									<div class="col col-12">
										<small class="text-muted font-weight-bold">
											Mon to Fri 9am to 6pm
										</small>
									</div>
								</div>
							</div>	
						</div>					
					</div>

					<div class="col col-12 my-4 ">
						<div class="row">
							<div class="col col-3 d-flex justify-content-center align-items-center">
								<i class="fas fa-envelope h4 mr-1"></i>
							</div>
							<div class="col">
								<div class="row">
									<div class="col col-12">
										<small class="font-weight-bolder" style="font-size:.9rem;">
											docmed@gmail.com
										</small>
									</div>
									<div class="col col-12">
										<small class="text-muted font-weight-bold">
											Send us your query<br>
											at any time
										</small>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>


		</div>		
	</div>
	
{% endblock %}

templates/create_symptoms_appointments.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}

{% block content %}
	{% if messages %}
		{% for message in messages %}
				<div class="alert alert-success w-75 mx-auto mt-3" role="alert">
					{{ message }}
				</div>
		{% endfor %}
	{% endif %}
	<form class="container w-75 jumbotron mt-4 py-2" id="login" method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" name="" class="btn btn-outline-primary mt-4">
	</form>
{% endblock %}

templates/doctor_appointment.html
{% extends 'home.html' %}

{% block content %}
	<table class="table table-hover table mt-4 w-75 border mx-auto">
	  <thead>
	    <tr>
	      <th scope="col">S.No</th>
	      <th scope="col">Date</th>
	      <th scope="col">Time</th>
	      <th scope="col">Patient</th>
	      <th scope="col">Status</th>
	    </tr>
	  </thead>
	  <tbody>
	    
	    {% for i in appointments %}
		    <tr>
		      <th scope="row">{{ forloop.counter }}</th>
		      <td>{{ i.date }}</td>
		      <td>{{ i.time }}</td>
		      <td>{{ i.patient }}</td>
		      <td>
		      	<a href="{% url 'main:doctor_prescription' id=i.id %}">
		      		{% if i.status == 'p' %}
		      			Pending
		      		{% else %}
		      			Completed
		      		{% endif %}
		      	</a>
		      </td>
		    </tr>
		{% endfor %}

	  </tbody>
	</table>
{% endblock %}

templates/doctor_form.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<style>
		.jumbotron {
			background: white;
			box-shadow: 5px 3px 20px rgba(0, 0, 0, .3);
			max-width: 700px;	
			transition: 400ms linear;	
		}

		.jumbotron:hover {
			transform: translateY(-4px);	
			transition: 400ms linear;
		}
	</style>
	{% if messages %}
		{% for message in messages %}
				<div class="alert alert-success w-75 mx-auto mt-3" role="alert">
					{{ message }}
				</div>
		{% endfor %}
	{% endif %}
	<form class="container w-75 jumbotron mt-4 py-2" id="login" method="POST">
		<h1 class="text-center text-uppercase h4 text-muted">UPDATE</h1>
		{% csrf_token %}
		{{ user_form|crispy }}
		{{ doctor_form|crispy }}
		<input type="submit" name="" class="btn btn-outline-primary mt-4">
	</form>
{% endblock %}

templates/home.html
	{% extends 'index.html' %}
{% load static %}

{% block content %}
<style>
	.alas:hover, .alas:hover > a {
		color: white;
	}

	.doc {
		color: orange;
		text-transform: uppercase;
	}

	@keyframes dj {
		from {
			transform: rotate(10deg);
		}
		to {
			transform: rotate(-10deg);
		}
	}
</style>
	<div id="home" style="min-height:calc(90vh);">
			<div class="row container m-auto">
				<div class="col d-none d-sm-none d-md-block col-md-4 alibaba" style="position: relative;perspective: 90px;top: 90px;">
					<img src="https://png.pngtree.com/png-vector/20200501/ourlarge/pngtree-corona-virus-svg-art-font-png-image_92286.jpg" class="docter"
						style="transform: rotateY(7deg); box-shadow: -4px -3px 2px rgba(0, 0, 0, .3);"
					 />
					<img src="{% static 'image/docter4.jpg' %}" class="docter"
					style="transform: rotateY(7deg); box-shadow: -4px -3px 2px rgba(0, 0, 0, .3);" />
				</div>
				<div class="col col-12 col-md-8 pt-5 lead">
						<p class="font-weight-bold">Welcome To <span class="doc">Docmed</span><p>
						<hr class="ml-0 bg-primary" style="width:10%;padding-top:1px;position:relative;bottom:10px;">
						<h3>Best Care For Your</h3>
						<h3 style="position: relative;bottom:5px;">Good Health</h3>
						<p class="text-justify w-75 text-danger">
							Are you one of those who have a very busy schedule and don't even have a time to take care of your health. Then you have landed on the right place.
						</p>
						<p>
							<i class="far fa-check-circle"></i>
							<small class="text-muted font-weight-bold ml-2">We have doctor from different corners of the world</small >
							<br>
							<i class="far fa-check-circle"></i>
							<small class="text-muted font-weight-bold ml-2">
								<b style="color:black">COVAT</b> chat bot who is always there to clear your queries
							</small >
							<br>
							<i class="far fa-check-circle"></i>
							<small class="text-muted font-weight-bold ml-2">
								<b style="color:black">ML Model</b> to help you detect covid based on your symptoms.
							</small >
							<br>
							<small class="text-muted font-weight-bold ml-2">
								Have your personal docter who is always there to assist you.
							</small >
						</p>
						<button class="btn btn-outline-primary btn-md alas"><a href="{% url 'main:register' %}" style="text-decoration: none;">Sign Up</a></button>
						<button class="btn btn-outline-primary btn-md ml-4 alas"><a href="{% url 'main:login' %}" style="text-decoration: none;">Sign In</a></button>
				</div>
			</div>
	</div>

	<div class="departments" id="department" style="min-height:100vh;">
		<h3 class="text-center pt-2">Our Departments</h3>
		<hr class="bg-primary" style="width: 3%;padding-top: 1px;position: relative;bottom: 5px;">
		<p class="text-muted text-center font-weight-bold">
			Estoom spirit tempair to say adious who direct asteem <br>
			it esteems luckily or picture placing drawing 
		</p>

		{% block card%}{% endblock %}

	</div>
	
	<!-- ending -->

	<div class="end container" style="min-height:100vh">
		<div class="d-flex justify-content-between py-4">
			<h5 class="font-weight-bolder">
				24 X 7 Service
				<hr class="w-50 bg-primary ml-0">
			</h5>
			<h5 class="font-weight-bolder">
				Qualified Doctor
				<hr class="w-50 bg-primary ml-0">			
			</h5>
			<h5 class="font-weight-bolder">
				Personal Assistance
				<hr class="w-50 bg-primary ml-0">
			</h5>
		</div>

		<div class="row mt-5 pt-4 lead">
			<div class="col ml-5">
				<i class="fa fa-camera text-primary h1 mt-5" aria-hidden="true"></i>
				<p>
					<span class="font-weight-bolder font-weight-bold lead mt-2 d-block">
						Let's Fight this pandemic together 
					</span>
					<br>
					<small class="mt-0 text-muted d-block lead" style="font-size: 1rem;">
						We the <b style="font-weight:bold;color:black">Docmed</b>  members understand what you all are 
						<br>
						going through during this pandemic time. But it's
						something 
						<br>
						which happend all of a sudden but it's not the end of the world
						<br>
						So let's take an oath that we won't do something which 
						<br>
						would make the sitation even more worse.
						<br>
						So we request you to follow the official guidelines and 
						<br>
						stay safe
						<br>
						<br>
						If you face any issue during this pandemic time then
						<br> 
						Docmed is always there to help you.

					</small>
				</p>
				<!-- <iframe  style="display: inline-block;position: relative;bottom:310px;left:600px;" width="600" height="415" src="https://www.trackcorona.live/map" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
			</div>
			<div class="col offset-1 col-5 last-image" style="overflow: hidden;">
				<img style="width:100%;overflow: hidden;" src="https://image.freepik.com/free-vector/thank-you-doctors-nurses_23-2148497069.jpg"
				>
			</div>
		</div>
		
	</div>

{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>DOCMED</title>
	<meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
	<link rel="icon" href="{% static  'image/fav.ICO' %}" type="image/gif" sizes="16x16">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
	<style>
		.covid {
			font-family: ubuntu;	
			color: wheat!important;
			font-size: 20px!important;
			animation: dj 4000ms linear infinite alternate;
			padding: 10px;
			border-radius: 10px;
		}

		@keyframes dj {
			0%, 100% {
				background: green;
				color: red;
			} 10% {
				background: lightgreen;
				color: maroon;
			}
		}
		.docter {
			transition: 500ms linear;	
		}
		.docter:hover {
			transition: 500ms linear;
			transform: translateY(-80px) rotateY(7deg)!important ;
		}

	</style>

</head>
		
<body>
	<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB7i_xGhQRURerOEpAOy5bP2vx7AQEp4dc&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
	<div style="min-height:10vh;">

			<div class="sec-nav py-3" style="font-size: 20px;">
				<img src="{% static 'image/main_logo.jpg' %}" class="main_logo">
				<span style="color:white" class="docmed d-none d-md-inline mr-3">Docmed</span>
				<div class="d-inline-block">
					<a href="{% url 'main:home' %}" class="mx-2 text-light">Home</a>
					<a href="{% url 'main:ml_models' %}" class="mx-2 text-light covid">Predict Covid</a>
					<a href="{% url 'main:contact' %}" class="mx-2 text-light">Contact</a>
					{% if request.user.user_category.is_patient %}
						<a href="{% url 'main:patient_appointment' %}" class="mx-2 text-light">Appointment</a>
						<a href="{% url 'main:patient_payment' %}" class="mx-2 text-light">Invoice & Payment</a>
						<a href="{% url 'main:patient_medical' %}" class="mx-2 text-light">Medical History</a>
						<a href="{% url 'main:patient_profile' %}" class="mx-2 text-light">Profile</a>
						<a href="{% url 'main:doctor_list' %}" class="mx-2 text-light">Doctors</a>
					{% elif request.user.user_category.is_doctor %}
						<a href="{% url 'main:doctor_appointment' %}" class="mx-2 text-light">Appointment</a>
						<a href="{% url 'main:doctor_prescriptions' %}" class="mx-2 text-light">Prescription</a>
						<a href="{% url 'main:doctor_profile' %}" class="mx-2 text-light">Profile</a>
					{% elif request.user.user_category.is_receptionist %}
						<a href="{% url 'main:receptionist_dashboard' %}" class="mx-2 text-light">Dashboard</a>
					{% elif request.user.user_category.is_hr %}
						<a href="{% url 'main:hr_dashboard' %}" class="mx-2 text-light">Dashboard</a>
						<a href="{% url 'main:accounting' %}" class="mx-2 text-light">Accounting</a>
					{% endif %}


					{% if user.is_authenticated %}
						<a href="{% url 'main:logout' %}" class="mx-2 text-light">Logout</a>	
					{% else %}
						<a href="{% url 'main:register' %}" class="mx-2 text-light">Sign Up</a>
						<a href="{% url 'main:login' %}" class="mx-2 text-light">Sign In</a>
					{% endif %}

				</div>

			</div>
	</div>
	{% block content %}{% endblock %}
</body>
	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'js/all.js' %}" ></script>
	<script type="text/javascript" src="{% static 'js/main.js' %}" ></script>
	
    <script type="text/javascript">
	    (function(d, m){
	        var kommunicateSettings = 
	            {"appId":"38b37405f0ee1d7154fadd1493ead09aa","popupWidget":true,"automaticChatOpenOnNavigation":true};
	        var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
	        s.src = "https://widget.kommunicate.io/v2/kommunicate.app";
	        var h = document.getElementsByTagName("head")[0]; h.appendChild(s);
	        window.kommunicate = m; m._globals = kommunicateSettings;
	    })(document, window.kommunicate || {});
	/* NOTE : Use web server to view HTML files as real-time update will not work if you directly open the HTML file in the browser. */
	</script>

</html>

templates/patient_form.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}

{% block content %}
<style>
	.jumbotron {
			background: white;
			box-shadow: 5px 3px 20px rgba(0, 0, 0, .3);
			max-width: 700px;	
			transition: 400ms linear;	
		}

		.jumbotron:hover {
			transform: translateY(-4px);	
			transition: 400ms linear;
		}
</style>
	{% if messages %}
		{% for message in messages %}
				<div class="alert alert-success w-75 mx-auto mt-3" role="alert">
					{{ message }}
				</div>
		{% endfor %}
	{% endif %}
	<form class="container w-75 jumbotron mt-4 py-2" id="login" method="POST">
		<h1 class="text-center text-uppercase h4 text-muted">UPDATE</h1>
		{% csrf_token %}
		{{ user_form|crispy }}
		{{ patient_form|crispy }}
		<input type="submit" name="" class="btn btn-outline-primary mt-4">
	</form>
{% endblock %}

templates/patient_payment.html
{% extends 'home.html' %}

{% block content %}
	<table class="table table-hover table mt-4 w-75 border mx-auto">
	  <thead>
	    <tr>
	      <th scope="col">S.No</th>
	      <th scope="col">Date</th>
	      <th scope="col">Time</th>
	      <th scope="col">Amount</th>
	      <th scope="col">Invoice</th>
	    </tr>
	  </thead>
	  <tbody>
	    
	    {% for i in appointments %}
		    <tr>
		      <th scope="row">{{ forloop.counter }}</th>
		      <td>{{ i.date }}</td>
		      <td>{{ i.time }}</td>
		      <td>{{ i.payment }} INR</td>
		      <td>
		      	<a href="{% url 'main:invoice' id=i.id %}">invoice</a>
		      </td>
		    </tr>
		{% endfor %}

	  </tbody>
	</table>
{% endblock %}

templates/receptionist_dashboard.html
{% extends 'home.html' %}

{% block content %}
	<div>
		<div class="row m-auto container">
			<div class="col col-4">
				<div class="department-card m-auto">
					<div class="card mt-3">
						<div class="card-header h5 bg-warning">
							Total Appointments
						</div>
						<div class="card-boby d-flex justify-content-center align-items-center bg-warning" style="height:100px;">
							<h1>
								{{ a }}
							</h1>
						</div>
					</div>
				</div>
			</div>

			<div class="col col-4">
				<div class="department-card m-auto">
					<div class="card mt-3">
						<div class="card-header h5 bg-warning">
							 Appointments Done
						</div>
						<div class="card-boby d-flex justify-content-center align-items-center bg-warning" style="height:100px;">
							<h1>
								{{ b }}
							</h1>
						</div>
					</div>
				</div>
			</div>

			<div class="col col-4">
				<div class="department-card m-auto">
					<div class="card mt-3">
						<div class="card-header h5 bg-warning">
							Upcoming Appointments
						</div>
						<div class="card-boby d-flex justify-content-center align-items-center bg-warning" style="height:100px;">
							<h1>
								{{ c }}
							</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row mt-3 mx-auto">
		<div class="col col-6">
			<div class="card p-2">
				<div class="card-header text-center bg-primary">
					<a href="{% url 'main:create_appointments' %}" class="btn btn-primary py-0">Create Appointments</a>
				</div>
				<div class="card-body">
					<table class="table table-hover table mt-1 w-100 border mx-auto">
					  <thead>
					  	{{ data }}
					    <tr>
					      <th scope="col">Date</th>
					      <th scope="col">Time</th>
					      <th scope="col">Doctor</th>
					      <th scope="col">Patient</th>
					      <th scope="col">Status</th>
					    </tr>
					  </thead>
					  <tbody>
					    
					    {% for i in appointments %}
						    <tr>
						      <td>{{ i.date }}</td>
						      <td>{{ i.time }}</td>
						      <td>{{ i.doctor }}</td>
						      <td>{{ i.patient }}</td>
						      <td>
						      		{% if i.status == 'p' %}
						      			Pending
						      		{% else %}
						      			Completed
						      		{% endif %}
						      </td>
						    </tr>
						{% endfor %}

					  </tbody>
					</table>
					
				</div>
			</div>
		</div>
		<div class="col col-6">
			<div class="card p-2">
				<div class="card-header text-center bg-primary">
					<h6 class="text-light " >Patients</h6>
				</div>
				<div class="card-body">
					<table class="table table-hover table mt-1 w-100 border mx-auto">
					  <thead>
					  	{{ data }}
					    <tr>
					      <th scope="col">Name</th>
					      <th scope="col">Phone</th>
					      <th scope="col">Gender</th>
					      <th scope="col">Age</th>
					      <th scope="col">Update</th>
					      <th scope="col">Delete</th>

					    </tr>
					  </thead>
					  <tbody>
					    
					    {% for i in patient %}
						    <tr>
						      <td>{{ i }}</td>
						      <td>{{ i.phone }}</td>
						      <td>{{ i.gender }}</td>
						      <td>{{ i.age }}</td>
						      <td><a href="{% url 'main:patient_profiles' id=i.id %}" class="btn btn-outline-primary p-1">Update</a></td>
						      <td><a href="{% url 'main:confirm_deletes' id=i.patient.user_category.id %}" class="btn btn-outline-danger p-1">Delete</a></td>

						    </tr>
						{% endfor %}

					  </tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock %}